version: '3.1'
services:
  mongo:
    container_name: luci-pizza-mongo
    image: mongo
    ports:
      - 27017:27017

  springboot:
    build: .
    container_name: luci-pizza-springboot
    image: luci-pizza
    restart: always
    ports:
      - 80:80
    depends_on:
      - mongo